[package]
name = "trustlang"
version = "0.0.1"
edition = "2021"

[features]
xid = ["orecc-front/xid"]

[dependencies]
# orecc-front = { path = "../../Libraries/orecc-front" }
orecc-front = { git = "https://github.com/InfiniteCoder01/orecc-front.git" }
orecc-back = { path = "../../Libraries/orecc-back" }

clap = { version = "4.4.0", features = ["derive"] }
rustyline = "12.0.0"
